name: Probros Linter Test-Cases

on: ["push", "pull_request"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install -r python/requirements_core.txt pytest
    - name: Run the tests with pytest
      run: |
        pytest python/pythia/linter/
